site_name: SWE AI Fleet
site_description: Multi-agent SWE at the edge. Local-first, open-source.
repo_url: https://github.com/tgarciai/swe-ai-fleet
repo_name: tgarciai/swe-ai-fleet
site_dir: site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            heading_level: 2
            separate_signature: true
            filters: ["!^_"]
            warn_on_error: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Guides:
      - Formatting: FORMATTING.md
      - Git Workflow: GIT_WORKFLOW.md
  - Architecture:
      - ADR: ADR-0001-license.md
      - RFCs:
          - RFC-0001: RFC-0001-bootstrap.md
          - RFC-0002: RFC-0002-persistent-scoped-memory.md
          - RFC-0003: RFC-0003-collaboration-flow.md
  - API Reference: api.md