phases:
  DESIGN:
    architect: [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL, DEPS_DECISIONS, MILESTONES, SUMMARY_LAST]
    developer: [CASE_HEADER, PLAN_HEADER, DECISIONS_RELEVANT_ROLE, DEPS_RELEVANT, SUMMARY_LAST]
    devops:    [CASE_HEADER, PLAN_HEADER, DECISIONS_RELEVANT_ROLE, DEPS_RELEVANT, MILESTONES]
    qa:        [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL, SUBTASKS_ALL, MILESTONES, SUMMARY_LAST]
    data:      [CASE_HEADER, PLAN_HEADER, DECISIONS_RELEVANT_ROLE, DEPS_RELEVANT]
  BUILD:
    architect: [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL, DEPS_DECISIONS, SUBTASKS_ALL, MILESTONES]
    developer: [CASE_HEADER, PLAN_HEADER, SUBTASKS_ROLE, DECISIONS_RELEVANT_ROLE, DEPS_RELEVANT]
    devops:    [CASE_HEADER, PLAN_HEADER, SUBTASKS_ROLE, DECISIONS_RELEVANT_ROLE, DEPS_RELEVANT]
    qa:        [CASE_HEADER, PLAN_HEADER, SUBTASKS_ALL_MIN, DECISIONS_GLOBAL_MIN, MILESTONES]
    data:      [CASE_HEADER, PLAN_HEADER, SUBTASKS_ROLE, DECISIONS_RELEVANT_ROLE]
  TEST:
    architect: [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL_MIN, SUBTASKS_ALL_MIN]
    developer: [CASE_HEADER, PLAN_HEADER, SUBTASKS_ROLE_MIN]
    devops:    [CASE_HEADER, PLAN_HEADER, SUBTASKS_ROLE_MIN]
    qa:        [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL, SUBTASKS_ALL, MILESTONES]
  DOC:
    architect: [CASE_HEADER, PLAN_HEADER, DECISIONS_GLOBAL, SUMMARY_LAST]
    qa:        [CASE_HEADER, PLAN_HEADER, SUBTASKS_ALL_MIN, MILESTONES]
