name: ci
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install
        run: |
          pip install -e .
          pip install pytest pytest-cov ruff
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest -m "not e2e and not integration" --cov=swe_ai_fleet --cov-report=xml
      - name: SonarCloud Scan
        if: ${{ secrets.SONAR_TOKEN != '' && secrets.SONAR_ORG != '' }}
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
  integration:
    if: false  # Disabled for now; placeholder for future implementation
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests are disabled for now"
